pong/player/urls.py
from django.urls import path
from . import views
from . import jwt

app_name = "player"

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('tfa/', views.tfa_view, name='tfa'),
    path('otp/', views.otp_view, name="otp"),
    path('account/', views.account_view, name="account"),
    path('auth/42/callback/', views.auth_42_callback, name='auth_42_callback'),
    path('logout/', views.logout_view, name='logout'),
    path('verify-jwt/', jwt.verify_jwt, name='verify_jwt'),
    path('update/', views.update_view, name='update'),
    path('update_password/', views.update_password_view, name='update_password'),
    path('delete_account/', views.delete_account_view, name='delete_account'),
]

pong/player/templates/player/account.html
{% extends 'layout.html' %}

{% block title %}
    MY ACCOUNT
{% endblock %}

{% block content %}
<br>
<h1>MY ACCOUNT</h1>
<br>
<h2>Infos</h2>
<br>

{% if user.profile_picture %}
    <img src="{{ user.profile_picture.url }}" alt="Profile Picture of {{ user.username }}" width ='200' height='150'>
    <br>
{% endif %}

<p>Nickname: {{ user.nickname }}</p>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Phone: {{ user.phone_number }}</p>
<p>ID: {{ user.id }}</p>
<p>Student: {{ user.student }}</p>
<p>Email 2FA: {{ user.email_2fa_active }}</p>
<p>SMS 2FA: {{ user.sms_2fa_active }}</p>
<br>

{% if not user.student %}
<a href="{% url 'player:update' %}">Edit info</a> <br>
<a href="{% url 'player:update_password' %}">Change password</a>
<br>
<br><hr>
<br>
<h2>Set 2FA (Double authentication)</h2>
<br>

<form method="post">
    {% csrf_token %}
    <h3>Email method</h3>
    <label>
        <input type="checkbox" id="email_2fa_active" name="email_2fa_active" {% if user.email_2fa_active %}checked{% endif %}>
        Activate Email 2FA
    </label>
    <br><br>

    {% if user.phone_number %}
    <h3>SMS method</h3>
    <label>
        <input type="checkbox" id="sms_2fa_active" name="sms_2fa_active" {% if user.sms_2fa_active %}checked{% endif %}>
        Activate SMS 2FA
        </label>
    <br><br>
    {% endif %}

    <button type="submit">Save</button>
</form>
<br>

{% endif %}

<hr>
<br>
<a href="{% url 'player:logout' %}">Log out</a> <br>

<br>
<a href="{% url 'player:delete_account' %}">Delete account</a> <br>

<br>
<a href="/privacy-policy">Privacy policy</a>

{% endblock %}

pong/player/templates/player/delete_account.html
{% extends 'layout.html' %}

{% block title %}
    DELETE ACCOUNT
{% endblock %}

{% block content %}
    <br>
    <h1>Delete account</h1>
    <br>
    
    <p>Before deleting your account, please read the <a href="/privacy-policy">privacy policy</a>.</p> <br>
    <p>If you want to delete your account, please contact us at:</p>

    <br><u>Email:</u> proj42_lh@proton.me
    <br><u>Address:</u> 20 Quai Frissard, 76600 Le Havre [FRANCE]
    <br><br>
    <p>We will let you know by email when your account will be deleted.</p>
    <br>

    {% endblock %}

pong/player/templates/player/login.html
{% extends 'layout.html' %}

{% block title %}
    Player Login
{% endblock %}

{% block content %}
    <br>
    <h1>Player Login</h1>
    <br>

    {% if error %}
        <p style="color: red;">{{ error }}</p>
        <br>
    {% endif %}
    
    <form class="form-width-validation" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" class="form-control" placeholder="Enter your username">
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" placeholder="Enter your password">
        </div>
        <br>

        <button type="submit" name="login">Log in</button>
    </form>
    <br>

    <form method="post">
        {% csrf_token %}
        <button type="submit" name="42_login">Log in with 42</button>
    </form>
    {% endblock %}

pong/player/templates/player/otp.html
{% extends 'layout.html' %}

{% block title %}
    OTP
{% endblock %}

{% block content %}
<br>
    <h1>OTP</h1>
    <br>
    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}

    <form  action="/player/otp/" method="POST">
        {% csrf_token %}
        <div>
            <label for="otp">OTP:</label>
            <input class="form" type="text" name="otp" required>
        </div>
        <br>
        <button type="submit">Confirm</button>
        <br>
    </form>
    <br>
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="resend_otp">Resend OTP</button>
    </form>
{% endblock %}

pong/player/templates/player/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
<br>

    <h1>Register a New User</h1>
    <form class="form-width-validation" action="/player/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <br><br>
        <label>
            <input type="checkbox" name="consent" required> I agree to the <a href="/privacy-policy">privacy policy</a>.
        </label>

        <br><br>
        <button>Submit</button>
    </form>
    
{% endblock %}

pong/player/templates/player/tfa.html
{% extends 'layout.html' %}

{% block title %}
    2FA
{% endblock %}

{% block content %}
    <br><h1>2FA</h1><br>

    <form  action="/player/tfa/" method="POST" >
        {% csrf_token %}
        
        {% if user.email_2fa_active %}
        <label>
            <input type="radio" name="otp_method" value="email" {% if user.email_2fa_active and not user.sms_2fa_active %} checked {% endif %}> Receive OTP via Email
        </label>
        <br>
        {% endif %}
        
        {% if user.sms_2fa_active %}
            <label>
                <input type="radio" name="otp_method" value="sms" {% if not user.email_2fa_active %} checked {% endif %}> Receive OTP via SMS
            </label>
            <br>
        {% endif %}

        <br>
        <button type="submit" name="tfa">Send OTP</button>
    </form>
{% endblock %}

pong/player/templates/player/update.html
{% extends 'layout.html' %}

{% block title %}
    Player Update
{% endblock %}

{% block content %}
    <br>
    <h1>Player Update</h1>
    <br>
    {% if messages %}
    {% for message in messages %}
        <h2 style="color: red">⚠️{{ message }}⚠️</h2>
    {% endfor %}
    {% endif %}
    <br>
    <form method="post" action="/player/update/" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="login">Update</button>
    </form>
    <br><br>
{% endblock %}

pong/player/templates/player/update_password.html
{% extends 'layout.html' %}

{% block title %}
    Change password
{% endblock %}
{% block content %}
<br><h1>Update Password</h1>
<br>
{% if form.errors %}
    <div class="alert alert-danger">
        <ul>
        {% for field in form %}
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
        </ul>
    </div>
{% endif %}
<br>

<form action="/player/update_password/" method="post">
    {% csrf_token %}
    
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}